# Generated by Django 2.2.6 on 2019-11-05 20:36

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_publicaciones', models.IntegerField()),
                ('no_usuarios', models.IntegerField()),
                ('tecnologias', multiselectfield.db.fields.MultiSelectField(choices=[('Andorid', 'Android'), ('IOS', 'IOS'), ('Web', 'Web')], max_length=15)),
                ('otras_funciones', models.BooleanField(default=False)),
                ('forma_pago', models.CharField(choices=[('Mensual', 'Mensual'), ('Anual', 'Anual')], max_length=50)),
                ('descuento', models.CharField(blank=True, max_length=50, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
