# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-11 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_publicaciones', models.IntegerField()),
                ('no_usuarios', models.IntegerField()),
                ('estadistica', models.BooleanField(default=False)),
                ('patrocinadores', models.BooleanField(default=False)),
                ('regitrso_sesion', models.BooleanField(default=False)),
                ('otras_funciones', models.BooleanField(default=False)),
                ('forma_pago', models.CharField(choices=[('Mensual', 'Mensual'), ('Anual', 'Anual')], max_length=50)),
                ('descuento', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
