# Generated by Django 2.2.6 on 2019-12-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizador',
            name='costo',
        ),
        migrations.AddField(
            model_name='cotizador',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cotizador',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
