# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-11 19:30
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizador',
            name='tecnologias',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Andorid', 'Android'), ('IOS', 'IOS'), ('Web', 'Web')], default=2, max_length=15),
            preserve_default=False,
        ),
    ]
