# Generated by Django 2.2.4 on 2019-09-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regiones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subregion',
            old_name='nombre_subregion',
            new_name='nombre_estado',
        ),
    ]
