# Generated by Django 2.2.6 on 2019-10-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('en_portada', models.BooleanField(default=False)),
                ('imagen', models.TextField()),
                ('redactado_por', models.CharField(blank=True, default='Equipo MX OPPORTUNITY', max_length=300, null=True)),
                ('status', models.CharField(choices=[('Publicado', 'Publicado'), ('No Publicado', 'No publicado')], default='Publicado', max_length=50)),
                ('cortesia_de', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_mostrada', models.DateField()),
                ('fecha_publicacion', models.DateTimeField()),
                ('fecha_fin', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
