# Generated by Django 2.2.5 on 2019-09-06 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('revista', '0001_initial'),
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_cat', to='revista.Categorias'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='origen_revista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_revista', to='revista.Revista'),
        ),
    ]
