# Generated by Django 2.2.4 on 2019-10-07 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('revista', '0001_initial'),
        ('patrocinadores', '0001_initial'),
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_cat', to='revista.Categorias'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='icon1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call1_icon', to='articulos.Icon'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='icon2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call2_icon', to='articulos.Icon'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='origen_revista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_revista', to='revista.Revista'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='patrocinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pat_articulo', to='patrocinadores.Patrocinador'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_subcat', to='revista.Subcategorias'),
        ),
    ]
