# Generated by Django 2.2.6 on 2019-11-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_auto_20191030_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='status',
            new_name='publicado',
        ),
    ]
