# Generated by Django 2.1.3 on 2019-11-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_auto_20191105_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='fecha_publicacion',
            field=models.DateField(),
        ),
    ]
