# Generated by Django 3.0.3 on 2020-02-21 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_auto_20191111_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='redactado_por',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Imagen', 'Imagen'), ('Texto', 'Texto'), ('Video', 'Video'), ('Publicidad', 'Publicidad')], max_length=200)),
                ('recurso', models.TextField()),
                ('alt', models.TextField(blank=True, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='con_art', to='articulos.Articulo')),
            ],
        ),
    ]
