# Generated by Django 2.1.3 on 2019-11-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrocinadores', '0002_patrocinador_revista_pertenencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrocinador',
            name='logo',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
