# Generated by Django 3.0.3 on 2020-02-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191111_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tipo_usuario',
        ),
    ]
