# Generated by Django 2.2.4 on 2019-09-17 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190917_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='revista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revista_perfil', to='revista.Revista'),
        ),
    ]
