# Generated by Django 3.0.3 on 2020-02-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
