# Generated by Django 3.0.3 on 2020-02-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200219_1953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
    ]
