<<<<<<< HEAD
# Generated by Django 2.2.4 on 2019-10-07 20:20
=======
# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-08 20:43
from __future__ import unicode_literals
>>>>>>> e202ef579cdf5f05dd87ce771ecdbfe1215d6957

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('revista', '0001_initial'),
=======
>>>>>>> e202ef579cdf5f05dd87ce771ecdbfe1215d6957
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
>>>>>>> e202ef579cdf5f05dd87ce771ecdbfe1215d6957
            name='Forma_Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('no_meses', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PlanRevista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('no_usuarios', models.CharField(max_length=5)),
                ('no_patrocinadores', models.CharField(max_length=5)),
                ('no_publicaciones_mensual', models.CharField(max_length=5)),
            ],
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('revista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='revista.Revista')),
                ('fecha_inicio', models.DateField()),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_contrato', to='planrevista.Forma_Pago')),
            ],
=======
        migrations.AddField(
            model_name='contrato',
            name='forma_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_contrato', to='planrevista.Forma_Pago'),
>>>>>>> e202ef579cdf5f05dd87ce771ecdbfe1215d6957
        ),
    ]
