<<<<<<< HEAD
# Generated by Django 2.1.3 on 2019-11-11 22:33
=======
# Generated by Django 2.1.3 on 2019-11-11 22:27
>>>>>>> origin/python

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('revista', '0001_initial'),
        ('planrevista', '0001_initial'),
=======
        ('planrevista', '0001_initial'),
        ('revista', '0001_initial'),
>>>>>>> origin/python
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='revista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revista_contrato', to='revista.Revista'),
        ),
    ]
