# Generated by Django 2.2.6 on 2019-10-18 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planrevista', '0001_initial'),
        ('revista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='revista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revista_contrato', to='revista.Revista'),
        ),
    ]
