# Generated by Django 2.2.4 on 2019-09-23 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planrevista', '0002_contrato_revista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='revista',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_revista', to='revista.Revista'),
        ),
    ]
