# Generated by Django 2.2.4 on 2019-09-23 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planrevista', '0003_auto_20190923_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='revista',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='revista.Revista'),
        ),
    ]
