# Generated by Django 2.2.4 on 2019-09-27 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planrevista', '0004_auto_20190923_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='id',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='revista',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='revista.Revista'),
        ),
    ]
