# Generated by Django 2.2.6 on 2019-11-05 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patrocinadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('recurso', models.TextField()),
                ('texto', models.TextField(blank=True, null=True)),
                ('accion', models.CharField(choices=[('Contactar', 'Contactar'), ('Visitar', 'Visitar'), ('Compar', 'Comprar'), ('Llamar', 'Llamar'), ('Sin llamada', 'Sin llamada')], max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('patrocinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pub_pat', to='patrocinadores.Patrocinador')),
            ],
        ),
    ]
