# Generated by Django 2.2.5 on 2019-09-06 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('planrevista', '0001_initial'),
        ('revista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='plan_contratado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_cliente', to='planrevista.PlanRevista'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='revista_pertenencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revista_origen', to='revista.Revista'),
        ),
    ]
