# Generated by Django 2.2.6 on 2019-10-15 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('revista', '0001_initial'),
        ('planrevista', '0001_initial'),
        ('regiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revista_plan', to='planrevista.PlanRevista'),
        ),
        migrations.AddField(
            model_name='revista',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revista_estado', to='regiones.Subregion'),
        ),
        migrations.AddField(
            model_name='categorias',
            name='revista_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_revista', to='revista.Revista'),
        ),
    ]
