# Generated by Django 2.2.4 on 2019-10-14 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revista',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revista_ciudad', to='regiones.Ciudad'),
        ),
        migrations.AlterField(
            model_name='revista',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revista_pais', to='regiones.Region'),
        ),
        migrations.AlterField(
            model_name='revista',
            name='logo',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='revista',
            name='nombre_revista',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='revista',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revista_plan', to='planrevista.PlanRevista'),
        ),
        migrations.AlterField(
            model_name='revista',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revista_estado', to='regiones.Subregion'),
        ),
    ]
