# Generated by Django 3.0.3 on 2020-02-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0003_auto_20200219_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revista',
            name='plan',
        ),
    ]
