# Generated by Django 2.1.3 on 2019-11-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regiones', '0001_initial'),
        ('revista', '0003_auto_20191113_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revista',
            name='country',
        ),
        migrations.AddField(
            model_name='revista',
            name='country',
            field=models.ManyToManyField(to='regiones.Region'),
        ),
    ]
